name: PR Automation
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - labeled

jobs:
  pr-automation:
    runs-on: ubuntu-latest

    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    # Specifically look for me
    - uses: alexwilson/enable-github-automerge-action@main
      if: github.event.pull_request.user.login == 'mikesplain'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'mikesplain'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: alexwilson/enable-github-automerge-action@main
      if: contains(github.event.pull_request.labels.*.name, 'automerge')
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
